/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HangerImport } from './routes/hanger'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HangerIndexImport } from './routes/hanger/index'

// Create/Update Routes

const HangerRoute = HangerImport.update({
  id: '/hanger',
  path: '/hanger',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HangerIndexRoute = HangerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HangerRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/hanger': {
      id: '/hanger'
      path: '/hanger'
      fullPath: '/hanger'
      preLoaderRoute: typeof HangerImport
      parentRoute: typeof rootRoute
    }
    '/hanger/': {
      id: '/hanger/'
      path: '/'
      fullPath: '/hanger/'
      preLoaderRoute: typeof HangerIndexImport
      parentRoute: typeof HangerImport
    }
  }
}

// Create and export the route tree

interface HangerRouteChildren {
  HangerIndexRoute: typeof HangerIndexRoute
}

const HangerRouteChildren: HangerRouteChildren = {
  HangerIndexRoute: HangerIndexRoute,
}

const HangerRouteWithChildren =
  HangerRoute._addFileChildren(HangerRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hanger': typeof HangerRouteWithChildren
  '/hanger/': typeof HangerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hanger': typeof HangerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hanger': typeof HangerRouteWithChildren
  '/hanger/': typeof HangerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/hanger' | '/hanger/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/hanger'
  id: '__root__' | '/' | '/about' | '/hanger' | '/hanger/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HangerRoute: typeof HangerRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HangerRoute: HangerRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/hanger"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/hanger": {
      "filePath": "hanger.tsx",
      "children": [
        "/hanger/"
      ]
    },
    "/hanger/": {
      "filePath": "hanger/index.tsx",
      "parent": "/hanger"
    }
  }
}
ROUTE_MANIFEST_END */
