/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EngineImport } from './routes/engine'
import { Route as IndexImport } from './routes/index'
import { Route as HangarIndexImport } from './routes/hangar/index'

// Create/Update Routes

const EngineRoute = EngineImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HangarIndexRoute = HangarIndexImport.update({
  id: '/hangar/',
  path: '/hangar/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineImport
      parentRoute: typeof rootRoute
    }
    '/hangar/': {
      id: '/hangar/'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof HangarIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/hangar': typeof HangarIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/hangar': typeof HangarIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/hangar/': typeof HangarIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/engine' | '/hangar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/engine' | '/hangar'
  id: '__root__' | '/' | '/engine' | '/hangar/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineRoute: typeof EngineRoute
  HangarIndexRoute: typeof HangarIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineRoute: EngineRoute,
  HangarIndexRoute: HangarIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/engine",
        "/hangar/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/engine": {
      "filePath": "engine.tsx"
    },
    "/hangar/": {
      "filePath": "hangar/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
